<?php

/**
 * This file is part of InkRouter-PHP-SDK.
 *
 * Copyright (c) Opensoft (http://opensoftdev.com)
 *
 * The unauthorized use of this code outside the boundaries of
 * Opensoft is prohibited.
 */

namespace InkRouter\Response;

/**
 * Information about update from InkRouter
 *
 * @author Kirill Gusakov
 * @deprecated
 */
class Update
{
    /**
     * Contains a unique update ID
     *
     * @var int
     */
    private $id;

    /**
     * A step of production workflow like PRINT, CUT, etc.
     *
     * @var string
     */
    private $type;

    /**
     * Number of printed items (copies) of the product
     *
     * @var int
     */
    private $quantity;

    /**
     * Order item ID generated by an print customer
     *
     * @var string
     */
    private $orderItemId;

    /**
     * Update details
     *
     * @var string
     */
    private $comment;

    /**
     * @var string
     */
    private $replyUrl;

    /**
     * @var int
     */
    private $timestamp;

    /**
     * @var string
     */
    private $printCustomerInvoice;

    /**
     * @var string
     */
    private $misc;

    /**
     * @var string
     */
    private $trackingNumber;

    /**
     * @var float
     */
    private $weight;

    /**
     * @var float
     */
    private $cost;

    /**
     * @var string
     */
    private $printProviderInvoice;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return Update
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param string $type
     * @return Update
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * @param int $quantity
     * @return Update
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * @return string
     */
    public function getOrderItemId()
    {
        return $this->orderItemId;
    }

    /**
     * @param string $orderItemId
     * @return Update
     */
    public function setOrderItemId($orderItemId)
    {
        $this->orderItemId = $orderItemId;

        return $this;
    }

    /**
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * @param string $comment
     * @return Update
     */
    public function setComment($comment)
    {
        $this->comment = $comment;

        return $this;
    }

    /**
     * @return string
     */
    public function getReplyUrl()
    {
        return $this->replyUrl;
    }

    /**
     * @param string $replyUrl
     * @return Update
     */
    public function setReplyUrl($replyUrl)
    {
        $this->replyUrl = $replyUrl;

        return $this;
    }

    /**
     * @param float
     * @return Update
     */
    public function setCost($cost)
    {
        $this->cost = $cost;

        return $this;
    }

    /**
     * @return float
     */
    public function getCost()
    {
        return $this->cost;
    }

    /**
     * @param string $misc
     * @return Update
     */
    public function setMisc($misc)
    {
        $this->misc = $misc;

        return $this;
    }

    /**
     * @return string
     */
    public function getMisc()
    {
        return $this->misc;
    }

    /**
     * @param string $printCustomerInvoice
     * @return Update
     */
    public function setPrintCustomerInvoice($printCustomerInvoice)
    {
        $this->printCustomerInvoice = $printCustomerInvoice;

        return $this;
    }

    /**
     * @return string
     */
    public function getPrintCustomerInvoice()
    {
        return $this->printCustomerInvoice;
    }

    /**
     * @param string $printProviderInvoice
     * @return Update
     */
    public function setPrintProviderInvoice($printProviderInvoice)
    {
        $this->printProviderInvoice = $printProviderInvoice;

        return $this;
    }

    /**
     * @return string
     */
    public function getPrintProviderInvoice()
    {
        return $this->printProviderInvoice;
    }

    /**
     * @param int $timestamp
     * @return Update
     */
    public function setTimestamp($timestamp)
    {
        $this->timestamp = $timestamp;

        return $this;
    }

    /**
     * @return int
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * @param string $trackingNumber
     * @return Update
     */
    public function setTrackingNumber($trackingNumber)
    {
        $this->trackingNumber = $trackingNumber;

        return $this;
    }

    /**
     * @return string
     */
    public function getTrackingNumber()
    {
        return $this->trackingNumber;
    }

    /**
     * @param float $weight
     * @return Update
     */
    public function setWeight($weight)
    {
        $this->weight = $weight;

        return $this;
    }

    /**
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }
}
